# Config file for automatic testing at travis-ci.org

os:
  - linux
  - windows
  - osx

matrix:
  include:
    - env: ENV_FILE=".ci/travis/37-windows.yml"
    - env: ENV_FILE=".ci/travis/37-osx.yml"
    - env: ENV_FILE=".ci/travis/37-linux.yml"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "OSX"; fi 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH"; conda config --set always_yes yes --set changeps1 no; conda update conda; conda info; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo "Windows"; fi 

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - conda env create --file="${ENV_FILE}"

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bellockk
  password:
    secure: OKGXTy8z2JErBLpjX864AbAZ947McwZoD7kzkC+l8cXviURo1HBsF02DjVxRdpW5kTTa/KF0PAvgilZeDhRPrvXj8ZUfMvyAvnu8PJ9FSSD0Q8mDjUoubMqCkO1N4yYNXFjbhLbyRd8yobkcwwMJwxOD5GtUnR68HzizW/2WDM6xxvPwuj47vMsdOJ096VotWAmNb7vOZ7syPfmPWa3AvKBygCb/zWlBSs4DOc6enScplTTKFYgNXbQ7KueUuT7gfnT+o3oFF1V3MpAogTtErbjqhQR/3WiOk+wBA8YbYUqyz95xUDP49TGfeDwVrO5O6Se2s5rDWpPTi08p30RrcpFtmDadDsR9OrdIRAi1cScfXrCSwXi2H9EvoMTkdhDDRWcyJzaWFb7vTHSXM+jxIq/EtgZidXEUmkhGNsM91KiiuphNPFKh1t8ZEOne/HGDwdsK1FaYyj0xSyfhHIICIbDvsxbAxXRBFla4wX3JIQMShZaUDh71fse2KV0apN5Un+WTtYsTgwfjHzh+ljhjg72tj4ruciH1uSHbV6qPX390ZIWbUulgmIjDEGhyTRPqZumQ9H9VbdFlhQv0msQR3OjvyD4zkilZOZaEilKYoDZApnEasqULdOnJqFkWbQjW//ft5tltX5vPkjjkoQPHENfftuGvlzyDZuzPHfG8248=
  on:
    tags: true
    repo: bellockk/alphashape
    python: 3.6
