channels:
  - conda-forge
dependencies:
  - python=3.8
  - sphinx=3.2.1
  - scipy=1.5.0
  - geopandas=0.8.1
  - pip=20.2.2
  - geos=3.8.1
  - proj4=6.1.1
  - cartopy=0.18.0
  - pip:
    - m2r==0.2.1
    - sphinx-issues==1.2.0
    - sphinx-gallery==0.7.0
